#!/usr/bin/env sh

set -e

export GIT_DIR=/var/puppet-git-receiver/puppet.git

[ "$1" = '--update' ] && sudo -E -u puppet-git git fetch -v

sudo -E -u puppet-git /var/puppet-git-receiver/puppet.git/hooks/update refs/heads/master dummy HEAD
